name: algotrading
channels:
  - default
dependencies:
  - python=3.6
  - pip
  - pip:
    - pandas==1.1.4
    - numpy==1.19.4
    - robin_stocks==1.5.3
    - jupyter
    - ipykernel==5.3.4
    - lxml==4.6.2
    - matplotlib==3.3.3
    - yfinance==0.1.55
    - alpaca-trade-api==0.51.0
    - sklearn
    - seaborn
    - flake8==3.8.4
    - pytest==5.4.3
    - pytest-cov==2.10.1
    - pytest-xdist==1.33.0
